version: '3'

services:
  client:
    container_name: cellfie-client
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000