version: '3'

services:
  server:
    container_name: upload-api
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      API_PORT: $API_PORT
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - $API_PORT:$API_PORT
  frontend:
    container_name: cellfie-client
    build:
      context: ./client/
      dockerfile: Dockerfile-prod
      args: 
        NODE_ENV: production
        REACT_APP_API_ROOT: $REACT_APP_API_ROOT
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80 
    depends_on:
      - server