services:
  server:
    container_name: upload-api
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - $API_PORT:$API_PORT

  frontend:
    container_name: client
    build:
      args:
        NODE_ENV: production
        REACT_APP_API_ROOT: $REACT_APP_API_ROOT
      context: ./frontend/
      dockerfile: Dockerfile-prod
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 80:80